title:        API Portal
url:          http://api-portal.apievangelist.com
logo:         https://kinlane-productions.s3.amazonaws.com/api-evangelist/api-evangelist-logo-400.png
logo_width:   63
logo_bottom_padding: 10

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 100
paginate_path: "/news/page:num/"

categories_path : /categories.html
tags_path : /tags.html

org: api-evangelist
repo: api-portal
resource: portal
oauthio: qUDL4eZqKPFb41SwuWIYIwLR6jI

# Masthead title
masthead_link: http://api-portal.apievangelist.com/
masthead_font_size: 75
masthead_title: '{"API Portal"}'

# Feature
feature_title: API Guide
feature_link: http://apievangelist.com
feature_image_source: https://s3.amazonaws.com/kinlane-productions/whitepapers/api-guides-loading.jpg
feature_image_width: 40

# Project
project_image: https://kinlane-productions.s3.amazonaws.com/api-evangelist/api-evangelist-logo-400.png
project_summary: This is a template API portal, designed to show a healthy baseline for API operations, helping API providers be sucessful when deploying and managing their APIs. This site uses APIs.json as the core, providing a machine readable index of the API, and its supporting building blocks.

# Navigation
navigation:
  - label1: Home
    link1: /index.html
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 0
    padding: 0
    decorate: 0
  - label1: Getting Started
    link1: /getting-started/
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 60
    padding: 0
    decorate: 0
  - label1: Documentation
    link1: /documentation/
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 60
    padding: 0
    decorate: 0
  - label1: Code
    link1: /code/
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 60
    padding: 0
    decorate: 0
  - label1: Blog
    link1: /blog/
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 60
    padding: 0
    decorate: 0
  - label1: Support
    link1: /support/
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 60
    padding: 0
    decorate: 0
  - label1: Pricing
    link1: /pricing/
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 60
    padding: 0
    decorate: 0
  - label1: Return to API Evangelist
    link1: http://apievangelist.com
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 10
    padding: 5
    decorate: 1

# Footer Navigation
footernavigation:
  - label: API 100K View
    link: http://apievangelist.com
  - label: News
    link: /news/
  - label: Partners
    link: http://apievangelist.com/partners/
  - label: APIs.json
    link: http://apisjson.org
  - label: About Kin Lane
    link: http://kinlane.com
  - label: Branding Guidelines
    link: http://apievangelist.com/branding-guidelines.html
  - label: Contact
    link: http://kinlane.com/contacts/

# sponsors
sponsors_margin_top: 5
sponsors_padding_top: 10
sponsors_json_url: https://s3.amazonaws.com/kinlane-productions/json/sponsors.json

# Footer
footer_title: API Evangelist
footer_link: http://apievangelist.com
footer_image_source: https://s3.amazonaws.com/kinlane-productions/footer/empowered-by-you-banner.png
footer_image_width: 60

# curated
curated_desc: As I keep track on the world of APIs I curate news, blog posts, articles, and other research that I feel is relevant specifically to API deployment--these are the links I am including in my research.

# organizations
org_desc: As I keep track on the world of APIs and read through the information I am curating I keep an eye out for any company, institution, or other agency that is doing anything interesting with API deployment. These are the organizations I'm currently including in my API deployment research.

# tools
tools_desc: These are the open source API deployment tooling that I am tracking on as part of my research, and can be used to help in the API deployment process.
